// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_tokens.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAPITokensBySite = `-- name: CountAPITokensBySite :one
SELECT count(*) FROM api_tokens WHERE site_id = $1
`

func (q *Queries) CountAPITokensBySite(ctx context.Context, siteID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAPITokensBySite, siteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (site_id, user_id, name, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, site_id, user_id, name, token_hash, expires_at, last_used_at, created_at
`

type CreateAPITokenParams struct {
	SiteID    uuid.UUID
	UserID    uuid.UUID
	Name      string
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.SiteID,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIToken = `-- name: DeleteAPIToken :one
DELETE FROM api_tokens WHERE id = $1 AND site_id = $2
RETURNING name
`

type DeleteAPITokenParams struct {
	ID     uuid.UUID
	SiteID uuid.UUID
}

func (q *Queries) DeleteAPIToken(ctx context.Context, arg DeleteAPITokenParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteAPIToken, arg.ID, arg.SiteID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT t.id, t.name, t.user_id, u.email AS user_email,
       s.id AS site_id, s.name AS site_name, s.domains AS site_domains
FROM api_tokens t
JOIN sites s ON s.id = t.site_id
JOIN users o ON o.id = s.owner_id
JOIN users u ON u.id = t.user_id
WHERE t.token_hash = $1
  AND (t.expires_at IS NULL OR t.expires_at > now())
  AND u.active
  AND (s.owner_id = u.id OR (u.role = 'admin_orga' AND o.org_id = u.org_id))
`

type GetAPITokenByHashRow struct {
	ID          uuid.UUID
	Name        string
	UserID      uuid.UUID
	UserEmail   string
	SiteID      uuid.UUID
	SiteName    string
	SiteDomains []string
}

// GetAPITokenByHash authentifie un appel d'API. Un jeton crée des formulaires, donc
// il vaut par l'écriture du créateur (propriétaire du site, ou administrateur de
// l'organisation du propriétaire), et non par la lecture. Ce droit est vérifié à
// chaque appel : un jeton échu, ou dont le créateur n'écrit plus le site, est
// introuvable.
func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (GetAPITokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPITokenByHash, tokenHash)
	var i GetAPITokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.UserEmail,
		&i.SiteID,
		&i.SiteName,
		&i.SiteDomains,
	)
	return i, err
}

const listAPITokensBySite = `-- name: ListAPITokensBySite :many
SELECT t.id, t.name, t.expires_at, t.last_used_at, t.created_at, u.name AS user_name,
       coalesce(u.active AND (s.owner_id = u.id OR (u.role = 'admin_orga' AND o.org_id = u.org_id)), false)::bool AS has_access
FROM api_tokens t
JOIN sites s ON s.id = t.site_id
JOIN users o ON o.id = s.owner_id
JOIN users u ON u.id = t.user_id
WHERE t.site_id = $1
ORDER BY t.created_at
`

type ListAPITokensBySiteRow struct {
	ID         uuid.UUID
	Name       string
	ExpiresAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	CreatedAt  time.Time
	UserName   string
	HasAccess  bool
}

// has_access reprend ce que GetAPITokenByHash exige du créateur (compte actif,
// écriture du site) : la page du site signale ainsi un jeton qu'il ne peut plus
// faire valoir. L'échéance n'y entre pas, la page l'affiche à part.
func (q *Queries) ListAPITokensBySite(ctx context.Context, siteID uuid.UUID) ([]ListAPITokensBySiteRow, error) {
	rows, err := q.db.Query(ctx, listAPITokensBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPITokensBySiteRow
	for rows.Next() {
		var i ListAPITokensBySiteRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UserName,
			&i.HasAccess,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = now()
WHERE id = $1
  AND (last_used_at IS NULL OR last_used_at < now() - interval '1 minute')
`

// Une écriture par minute au plus : la date sert à repérer un jeton oublié, pas
// à compter les appels.
func (q *Queries) TouchAPIToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIToken, id)
	return err
}
