// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAttachment = `-- name: CreateAttachment :exec
INSERT INTO attachments (submission_id, position, filename, size, content)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAttachmentParams struct {
	SubmissionID uuid.UUID
	Position     int16
	Filename     string
	Size         int64
	Content      []byte
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) error {
	_, err := q.db.Exec(ctx, createAttachment,
		arg.SubmissionID,
		arg.Position,
		arg.Filename,
		arg.Size,
		arg.Content,
	)
	return err
}

const formHasAttachments = `-- name: FormHasAttachments :one
SELECT EXISTS (
    SELECT 1 FROM attachments a
    JOIN submissions sub ON sub.id = a.submission_id
    WHERE sub.form_id = $1
)
`

func (q *Queries) FormHasAttachments(ctx context.Context, formID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, formHasAttachments, formID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAttachmentScoped = `-- name: GetAttachmentScoped :one
SELECT a.filename, a.content
FROM attachments a
JOIN submissions sub ON sub.id = a.submission_id
JOIN forms f ON f.id = sub.form_id
JOIN sites s ON s.id = f.site_id
JOIN users o ON o.id = s.owner_id
WHERE a.id = $1
  AND (s.owner_id = $2
       OR o.org_id = $3::uuid
       OR EXISTS (SELECT 1 FROM site_read_grants g WHERE g.site_id = s.id AND g.user_id = $2))
`

type GetAttachmentScopedParams struct {
	ID         uuid.UUID
	ViewerID   uuid.UUID
	AdminOrgID pgtype.UUID
}

type GetAttachmentScopedRow struct {
	Filename string
	Content  []byte
}

// Même règle de cloisonnement que submissions.sql : le périmètre du demandeur
// est vérifié dans la requête, via le site propriétaire du formulaire.
func (q *Queries) GetAttachmentScoped(ctx context.Context, arg GetAttachmentScopedParams) (GetAttachmentScopedRow, error) {
	row := q.db.QueryRow(ctx, getAttachmentScoped, arg.ID, arg.ViewerID, arg.AdminOrgID)
	var i GetAttachmentScopedRow
	err := row.Scan(&i.Filename, &i.Content)
	return i, err
}

const listAttachmentsByForm = `-- name: ListAttachmentsByForm :many
SELECT a.id, a.submission_id, a.position, a.filename
FROM attachments a
JOIN submissions sub ON sub.id = a.submission_id
WHERE sub.form_id = $1
ORDER BY sub.created_at, sub.id, a.position
`

type ListAttachmentsByFormRow struct {
	ID           uuid.UUID
	SubmissionID uuid.UUID
	Position     int16
	Filename     string
}

// ListAttachmentsByForm alimente l'export en archive, dans l'ordre de l'export
// CSV. Sans le contenu : il est lu fichier par fichier, pour ne pas tenir en
// mémoire celui de toutes les pièces jointes d'un formulaire.
func (q *Queries) ListAttachmentsByForm(ctx context.Context, formID uuid.UUID) ([]ListAttachmentsByFormRow, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByForm, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttachmentsByFormRow
	for rows.Next() {
		var i ListAttachmentsByFormRow
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.Position,
			&i.Filename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsBySubmission = `-- name: ListAttachmentsBySubmission :many
SELECT id, filename, size FROM attachments
WHERE submission_id = $1
ORDER BY position
`

type ListAttachmentsBySubmissionRow struct {
	ID       uuid.UUID
	Filename string
	Size     int64
}

// ListAttachmentsBySubmission alimente la fiche d'une soumission : sans le
// contenu, qui n'est lu qu'au téléchargement.
func (q *Queries) ListAttachmentsBySubmission(ctx context.Context, submissionID uuid.UUID) ([]ListAttachmentsBySubmissionRow, error) {
	rows, err := q.db.Query(ctx, listAttachmentsBySubmission, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttachmentsBySubmissionRow
	for rows.Next() {
		var i ListAttachmentsBySubmissionRow
		if err := rows.Scan(&i.ID, &i.Filename, &i.Size); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
