// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (actor_id, action, entity, entity_id, detail)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAuditLogParams struct {
	ActorID  pgtype.UUID
	Action   string
	Entity   string
	EntityID pgtype.UUID
	Detail   *string
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ActorID,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.Detail,
	)
	return err
}

const purgeAuditOlderThan = `-- name: PurgeAuditOlderThan :exec
DELETE FROM audit_log WHERE created_at < now() - make_interval(days => $1::int)
`

func (q *Queries) PurgeAuditOlderThan(ctx context.Context, dollar_1 int32) error {
	_, err := q.db.Exec(ctx, purgeAuditOlderThan, dollar_1)
	return err
}

const scrubAuditIPOlderThan = `-- name: ScrubAuditIPOlderThan :exec
UPDATE audit_log SET detail = (detail::jsonb - 'ip')::text
WHERE created_at < now() - make_interval(days => $1::int)
  AND detail LIKE '%"ip"%'
`

func (q *Queries) ScrubAuditIPOlderThan(ctx context.Context, dollar_1 int32) error {
	_, err := q.db.Exec(ctx, scrubAuditIPOlderThan, dollar_1)
	return err
}
