// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backup_codes.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const countUnusedBackupCodes = `-- name: CountUnusedBackupCodes :one
SELECT count(*) FROM totp_backup_codes WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) CountUnusedBackupCodes(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnusedBackupCodes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBackupCode = `-- name: CreateBackupCode :exec
INSERT INTO totp_backup_codes (user_id, code_hash) VALUES ($1, $2)
`

type CreateBackupCodeParams struct {
	UserID   uuid.UUID
	CodeHash string
}

func (q *Queries) CreateBackupCode(ctx context.Context, arg CreateBackupCodeParams) error {
	_, err := q.db.Exec(ctx, createBackupCode, arg.UserID, arg.CodeHash)
	return err
}

const deleteBackupCodes = `-- name: DeleteBackupCodes :exec
DELETE FROM totp_backup_codes WHERE user_id = $1
`

func (q *Queries) DeleteBackupCodes(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBackupCodes, userID)
	return err
}

const listUnusedBackupCodes = `-- name: ListUnusedBackupCodes :many
SELECT id, code_hash FROM totp_backup_codes WHERE user_id = $1 AND used_at IS NULL
`

type ListUnusedBackupCodesRow struct {
	ID       uuid.UUID
	CodeHash string
}

func (q *Queries) ListUnusedBackupCodes(ctx context.Context, userID uuid.UUID) ([]ListUnusedBackupCodesRow, error) {
	rows, err := q.db.Query(ctx, listUnusedBackupCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnusedBackupCodesRow
	for rows.Next() {
		var i ListUnusedBackupCodesRow
		if err := rows.Scan(&i.ID, &i.CodeHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBackupCodeUsed = `-- name: MarkBackupCodeUsed :exec
UPDATE totp_backup_codes SET used_at = now() WHERE id = $1
`

func (q *Queries) MarkBackupCodeUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markBackupCodeUsed, id)
	return err
}
