// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blocked_senders.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addBlockedSender = `-- name: AddBlockedSender :exec
INSERT INTO site_blocked_senders (site_id, value) VALUES ($1, $2)
ON CONFLICT (site_id, value) DO NOTHING
`

type AddBlockedSenderParams struct {
	SiteID uuid.UUID
	Value  string
}

func (q *Queries) AddBlockedSender(ctx context.Context, arg AddBlockedSenderParams) error {
	_, err := q.db.Exec(ctx, addBlockedSender, arg.SiteID, arg.Value)
	return err
}

const isSenderBlocked = `-- name: IsSenderBlocked :one
SELECT EXISTS (SELECT 1 FROM site_blocked_senders WHERE site_id = $1 AND value = ANY($2::text[]))
`

type IsSenderBlockedParams struct {
	SiteID uuid.UUID
	Keys   []string
}

// The keys come from submission.SenderKeys, already lower-cased like the stored values.
func (q *Queries) IsSenderBlocked(ctx context.Context, arg IsSenderBlockedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isSenderBlocked, arg.SiteID, arg.Keys)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listBlockedSenders = `-- name: ListBlockedSenders :many
SELECT id, site_id, value, created_at FROM site_blocked_senders WHERE site_id = $1 ORDER BY value
`

func (q *Queries) ListBlockedSenders(ctx context.Context, siteID uuid.UUID) ([]SiteBlockedSender, error) {
	rows, err := q.db.Query(ctx, listBlockedSenders, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SiteBlockedSender
	for rows.Next() {
		var i SiteBlockedSender
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeBlockedSender = `-- name: RemoveBlockedSender :one
DELETE FROM site_blocked_senders WHERE id = $1 AND site_id = $2
RETURNING value
`

type RemoveBlockedSenderParams struct {
	ID     uuid.UUID
	SiteID uuid.UUID
}

func (q *Queries) RemoveBlockedSender(ctx context.Context, arg RemoveBlockedSenderParams) (string, error) {
	row := q.db.QueryRow(ctx, removeBlockedSender, arg.ID, arg.SiteID)
	var value string
	err := row.Scan(&value)
	return value, err
}
