// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: forms.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countFormsBySite = `-- name: CountFormsBySite :one
SELECT count(*) FROM forms WHERE site_id = $1
`

func (q *Queries) CountFormsBySite(ctx context.Context, siteID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFormsBySite, siteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createForm = `-- name: CreateForm :one
INSERT INTO forms (site_id, name, access_key, notify_email, recipients, email_include_content, store_submissions, retention_days, redirect_url,
                   slack_webhook_url, teams_webhook_url, discord_webhook_url, chat_include_content,
                   telegram_bot_token, telegram_chat_id, accept_attachments, captcha, notification_lang)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
RETURNING id, site_id, name, access_key, active, notify_email, recipients, email_include_content, store_submissions, retention_days, redirect_url, created_at, updated_at, slack_webhook_url, teams_webhook_url, chat_include_content, discord_webhook_url, telegram_bot_token, telegram_chat_id, accept_attachments, captcha, notification_lang
`

type CreateFormParams struct {
	SiteID              uuid.UUID
	Name                string
	AccessKey           string
	NotifyEmail         bool
	Recipients          []string
	EmailIncludeContent bool
	StoreSubmissions    bool
	RetentionDays       int32
	RedirectUrl         *string
	SlackWebhookUrl     *string
	TeamsWebhookUrl     *string
	DiscordWebhookUrl   *string
	ChatIncludeContent  bool
	TelegramBotToken    *string
	TelegramChatID      *string
	AcceptAttachments   bool
	Captcha             bool
	NotificationLang    string
}

func (q *Queries) CreateForm(ctx context.Context, arg CreateFormParams) (Form, error) {
	row := q.db.QueryRow(ctx, createForm,
		arg.SiteID,
		arg.Name,
		arg.AccessKey,
		arg.NotifyEmail,
		arg.Recipients,
		arg.EmailIncludeContent,
		arg.StoreSubmissions,
		arg.RetentionDays,
		arg.RedirectUrl,
		arg.SlackWebhookUrl,
		arg.TeamsWebhookUrl,
		arg.DiscordWebhookUrl,
		arg.ChatIncludeContent,
		arg.TelegramBotToken,
		arg.TelegramChatID,
		arg.AcceptAttachments,
		arg.Captcha,
		arg.NotificationLang,
	)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.AccessKey,
		&i.Active,
		&i.NotifyEmail,
		&i.Recipients,
		&i.EmailIncludeContent,
		&i.StoreSubmissions,
		&i.RetentionDays,
		&i.RedirectUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SlackWebhookUrl,
		&i.TeamsWebhookUrl,
		&i.ChatIncludeContent,
		&i.DiscordWebhookUrl,
		&i.TelegramBotToken,
		&i.TelegramChatID,
		&i.AcceptAttachments,
		&i.Captcha,
		&i.NotificationLang,
	)
	return i, err
}

const deleteFormScoped = `-- name: DeleteFormScoped :execrows
DELETE FROM forms
WHERE forms.id = $1
  AND forms.site_id IN (SELECT s.id FROM sites s
                  WHERE s.owner_id = $2
                     OR s.owner_id IN (SELECT u.id FROM users u WHERE u.org_id = $3::uuid))
`

type DeleteFormScopedParams struct {
	ID         uuid.UUID
	ViewerID   uuid.UUID
	AdminOrgID pgtype.UUID
}

func (q *Queries) DeleteFormScoped(ctx context.Context, arg DeleteFormScopedParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFormScoped, arg.ID, arg.ViewerID, arg.AdminOrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFormByAccessKey = `-- name: GetFormByAccessKey :one
SELECT f.id, f.site_id, f.name, f.access_key, f.active, f.notify_email, f.recipients, f.email_include_content, f.store_submissions, f.retention_days, f.redirect_url, f.created_at, f.updated_at, f.slack_webhook_url, f.teams_webhook_url, f.chat_include_content, f.discord_webhook_url, f.telegram_bot_token, f.telegram_chat_id, f.accept_attachments, f.captcha, f.notification_lang, s.name AS site_name, s.domains AS site_domains
FROM forms f
JOIN sites s ON s.id = f.site_id
WHERE f.access_key = $1
`

type GetFormByAccessKeyRow struct {
	ID                  uuid.UUID
	SiteID              uuid.UUID
	Name                string
	AccessKey           string
	Active              bool
	NotifyEmail         bool
	Recipients          []string
	EmailIncludeContent bool
	StoreSubmissions    bool
	RetentionDays       int32
	RedirectUrl         *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	SlackWebhookUrl     *string
	TeamsWebhookUrl     *string
	ChatIncludeContent  bool
	DiscordWebhookUrl   *string
	TelegramBotToken    *string
	TelegramChatID      *string
	AcceptAttachments   bool
	Captcha             bool
	NotificationLang    string
	SiteName            string
	SiteDomains         []string
}

// GetFormByAccessKey sert le point d'entrée public : aucune notion d'utilisateur,
// la clé d'accès désigne le formulaire.
func (q *Queries) GetFormByAccessKey(ctx context.Context, accessKey string) (GetFormByAccessKeyRow, error) {
	row := q.db.QueryRow(ctx, getFormByAccessKey, accessKey)
	var i GetFormByAccessKeyRow
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.AccessKey,
		&i.Active,
		&i.NotifyEmail,
		&i.Recipients,
		&i.EmailIncludeContent,
		&i.StoreSubmissions,
		&i.RetentionDays,
		&i.RedirectUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SlackWebhookUrl,
		&i.TeamsWebhookUrl,
		&i.ChatIncludeContent,
		&i.DiscordWebhookUrl,
		&i.TelegramBotToken,
		&i.TelegramChatID,
		&i.AcceptAttachments,
		&i.Captcha,
		&i.NotificationLang,
		&i.SiteName,
		&i.SiteDomains,
	)
	return i, err
}

const getFormScoped = `-- name: GetFormScoped :one
SELECT f.id, f.site_id, f.name, f.access_key, f.active, f.notify_email, f.recipients, f.email_include_content, f.store_submissions, f.retention_days, f.redirect_url, f.created_at, f.updated_at, f.slack_webhook_url, f.teams_webhook_url, f.chat_include_content, f.discord_webhook_url, f.telegram_bot_token, f.telegram_chat_id, f.accept_attachments, f.captcha, f.notification_lang, s.name AS site_name, s.domains AS site_domains,
       coalesce(s.owner_id = $1 OR o.org_id = $2::uuid, false)::bool AS can_write
FROM forms f
JOIN sites s ON s.id = f.site_id
JOIN users o ON o.id = s.owner_id
WHERE f.id = $3
  AND (s.owner_id = $1
       OR o.org_id = $2::uuid
       OR EXISTS (SELECT 1 FROM site_read_grants g WHERE g.site_id = s.id AND g.user_id = $1))
`

type GetFormScopedParams struct {
	ViewerID   uuid.UUID
	AdminOrgID pgtype.UUID
	ID         uuid.UUID
}

type GetFormScopedRow struct {
	ID                  uuid.UUID
	SiteID              uuid.UUID
	Name                string
	AccessKey           string
	Active              bool
	NotifyEmail         bool
	Recipients          []string
	EmailIncludeContent bool
	StoreSubmissions    bool
	RetentionDays       int32
	RedirectUrl         *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	SlackWebhookUrl     *string
	TeamsWebhookUrl     *string
	ChatIncludeContent  bool
	DiscordWebhookUrl   *string
	TelegramBotToken    *string
	TelegramChatID      *string
	AcceptAttachments   bool
	Captcha             bool
	NotificationLang    string
	SiteName            string
	SiteDomains         []string
	CanWrite            bool
}

// Même règle de cloisonnement que sites.sql, appliquée au site du formulaire.
func (q *Queries) GetFormScoped(ctx context.Context, arg GetFormScopedParams) (GetFormScopedRow, error) {
	row := q.db.QueryRow(ctx, getFormScoped, arg.ViewerID, arg.AdminOrgID, arg.ID)
	var i GetFormScopedRow
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.AccessKey,
		&i.Active,
		&i.NotifyEmail,
		&i.Recipients,
		&i.EmailIncludeContent,
		&i.StoreSubmissions,
		&i.RetentionDays,
		&i.RedirectUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SlackWebhookUrl,
		&i.TeamsWebhookUrl,
		&i.ChatIncludeContent,
		&i.DiscordWebhookUrl,
		&i.TelegramBotToken,
		&i.TelegramChatID,
		&i.AcceptAttachments,
		&i.Captcha,
		&i.NotificationLang,
		&i.SiteName,
		&i.SiteDomains,
		&i.CanWrite,
	)
	return i, err
}

const listFormsBySite = `-- name: ListFormsBySite :many
SELECT f.id, f.site_id, f.name, f.access_key, f.active, f.notify_email, f.recipients, f.email_include_content, f.store_submissions, f.retention_days, f.redirect_url, f.created_at, f.updated_at, f.slack_webhook_url, f.teams_webhook_url, f.chat_include_content, f.discord_webhook_url, f.telegram_bot_token, f.telegram_chat_id, f.accept_attachments, f.captcha, f.notification_lang,
       (SELECT count(*) FROM submissions sub WHERE sub.form_id = f.id) AS submission_count,
       (SELECT count(*) FROM submissions sub WHERE sub.form_id = f.id AND sub.read_at IS NULL) AS unread_count
FROM forms f
WHERE f.site_id = $1
ORDER BY f.name
`

type ListFormsBySiteRow struct {
	ID                  uuid.UUID
	SiteID              uuid.UUID
	Name                string
	AccessKey           string
	Active              bool
	NotifyEmail         bool
	Recipients          []string
	EmailIncludeContent bool
	StoreSubmissions    bool
	RetentionDays       int32
	RedirectUrl         *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	SlackWebhookUrl     *string
	TeamsWebhookUrl     *string
	ChatIncludeContent  bool
	DiscordWebhookUrl   *string
	TelegramBotToken    *string
	TelegramChatID      *string
	AcceptAttachments   bool
	Captcha             bool
	NotificationLang    string
	SubmissionCount     int64
	UnreadCount         int64
}

func (q *Queries) ListFormsBySite(ctx context.Context, siteID uuid.UUID) ([]ListFormsBySiteRow, error) {
	rows, err := q.db.Query(ctx, listFormsBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFormsBySiteRow
	for rows.Next() {
		var i ListFormsBySiteRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Name,
			&i.AccessKey,
			&i.Active,
			&i.NotifyEmail,
			&i.Recipients,
			&i.EmailIncludeContent,
			&i.StoreSubmissions,
			&i.RetentionDays,
			&i.RedirectUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SlackWebhookUrl,
			&i.TeamsWebhookUrl,
			&i.ChatIncludeContent,
			&i.DiscordWebhookUrl,
			&i.TelegramBotToken,
			&i.TelegramChatID,
			&i.AcceptAttachments,
			&i.Captcha,
			&i.NotificationLang,
			&i.SubmissionCount,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFormsOfSite = `-- name: ListFormsOfSite :many
SELECT id, site_id, name, access_key, active, notify_email, recipients, email_include_content, store_submissions, retention_days, redirect_url, created_at, updated_at, slack_webhook_url, teams_webhook_url, chat_include_content, discord_webhook_url, telegram_bot_token, telegram_chat_id, accept_attachments, captcha, notification_lang FROM forms WHERE site_id = $1 ORDER BY name
`

// ListFormsOfSite et CountFormsBySite servent l'API. Pas de périmètre dans ces
// requêtes : le site vient du jeton, que GetAPITokenByHash a déjà contrôlé.
func (q *Queries) ListFormsOfSite(ctx context.Context, siteID uuid.UUID) ([]Form, error) {
	rows, err := q.db.Query(ctx, listFormsOfSite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Form
	for rows.Next() {
		var i Form
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Name,
			&i.AccessKey,
			&i.Active,
			&i.NotifyEmail,
			&i.Recipients,
			&i.EmailIncludeContent,
			&i.StoreSubmissions,
			&i.RetentionDays,
			&i.RedirectUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SlackWebhookUrl,
			&i.TeamsWebhookUrl,
			&i.ChatIncludeContent,
			&i.DiscordWebhookUrl,
			&i.TelegramBotToken,
			&i.TelegramChatID,
			&i.AcceptAttachments,
			&i.Captcha,
			&i.NotificationLang,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFormAccessKeyScoped = `-- name: SetFormAccessKeyScoped :execrows
UPDATE forms SET access_key = $1, updated_at = now()
WHERE forms.id = $2
  AND forms.site_id IN (SELECT s.id FROM sites s
                  WHERE s.owner_id = $3
                     OR s.owner_id IN (SELECT u.id FROM users u WHERE u.org_id = $4::uuid))
`

type SetFormAccessKeyScopedParams struct {
	AccessKey  string
	ID         uuid.UUID
	ViewerID   uuid.UUID
	AdminOrgID pgtype.UUID
}

func (q *Queries) SetFormAccessKeyScoped(ctx context.Context, arg SetFormAccessKeyScopedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setFormAccessKeyScoped,
		arg.AccessKey,
		arg.ID,
		arg.ViewerID,
		arg.AdminOrgID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateFormScoped = `-- name: UpdateFormScoped :execrows
UPDATE forms
SET name = $1, active = $2, notify_email = $3,
    recipients = $4, email_include_content = $5,
    store_submissions = $6, retention_days = $7,
    redirect_url = $8,
    slack_webhook_url = $9, teams_webhook_url = $10,
    discord_webhook_url = $11, chat_include_content = $12,
    telegram_bot_token = $13, telegram_chat_id = $14,
    accept_attachments = $15, captcha = $16,
    notification_lang = $17, updated_at = now()
WHERE forms.id = $18
  AND forms.site_id IN (SELECT s.id FROM sites s
                  WHERE s.owner_id = $19
                     OR s.owner_id IN (SELECT u.id FROM users u WHERE u.org_id = $20::uuid))
`

type UpdateFormScopedParams struct {
	Name                string
	Active              bool
	NotifyEmail         bool
	Recipients          []string
	EmailIncludeContent bool
	StoreSubmissions    bool
	RetentionDays       int32
	RedirectUrl         *string
	SlackWebhookUrl     *string
	TeamsWebhookUrl     *string
	DiscordWebhookUrl   *string
	ChatIncludeContent  bool
	TelegramBotToken    *string
	TelegramChatID      *string
	AcceptAttachments   bool
	Captcha             bool
	NotificationLang    string
	ID                  uuid.UUID
	ViewerID            uuid.UUID
	AdminOrgID          pgtype.UUID
}

// Écritures sur un formulaire : même condition d'écriture que sites.sql, par le
// site du formulaire. Une lecture seule ne les passe jamais.
func (q *Queries) UpdateFormScoped(ctx context.Context, arg UpdateFormScopedParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFormScoped,
		arg.Name,
		arg.Active,
		arg.NotifyEmail,
		arg.Recipients,
		arg.EmailIncludeContent,
		arg.StoreSubmissions,
		arg.RetentionDays,
		arg.RedirectUrl,
		arg.SlackWebhookUrl,
		arg.TeamsWebhookUrl,
		arg.DiscordWebhookUrl,
		arg.ChatIncludeContent,
		arg.TelegramBotToken,
		arg.TelegramChatID,
		arg.AcceptAttachments,
		arg.Captcha,
		arg.NotificationLang,
		arg.ID,
		arg.ViewerID,
		arg.AdminOrgID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
