// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: forms.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countFormsBySite = `-- name: CountFormsBySite :one
SELECT count(*) FROM forms WHERE site_id = $1
`

func (q *Queries) CountFormsBySite(ctx context.Context, siteID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFormsBySite, siteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createForm = `-- name: CreateForm :one
INSERT INTO forms (site_id, name, access_key, notify_email, recipients, email_include_content, store_submissions, retention_days, redirect_url,
                   slack_webhook_url, teams_webhook_url, discord_webhook_url, chat_include_content,
                   telegram_bot_token, telegram_chat_id, accept_attachments, captcha, notification_lang)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
RETURNING id, site_id, name, access_key, active, notify_email, recipients, email_include_content, store_submissions, retention_days, redirect_url, created_at, updated_at, slack_webhook_url, teams_webhook_url, chat_include_content, discord_webhook_url, telegram_bot_token, telegram_chat_id, accept_attachments, captcha, notification_lang
`

type CreateFormParams struct {
	SiteID              uuid.UUID
	Name                string
	AccessKey           string
	NotifyEmail         bool
	Recipients          []string
	EmailIncludeContent bool
	StoreSubmissions    bool
	RetentionDays       int32
	RedirectUrl         *string
	SlackWebhookUrl     *string
	TeamsWebhookUrl     *string
	DiscordWebhookUrl   *string
	ChatIncludeContent  bool
	TelegramBotToken    *string
	TelegramChatID      *string
	AcceptAttachments   bool
	Captcha             bool
	NotificationLang    string
}

func (q *Queries) CreateForm(ctx context.Context, arg CreateFormParams) (Form, error) {
	row := q.db.QueryRow(ctx, createForm,
		arg.SiteID,
		arg.Name,
		arg.AccessKey,
		arg.NotifyEmail,
		arg.Recipients,
		arg.EmailIncludeContent,
		arg.StoreSubmissions,
		arg.RetentionDays,
		arg.RedirectUrl,
		arg.SlackWebhookUrl,
		arg.TeamsWebhookUrl,
		arg.DiscordWebhookUrl,
		arg.ChatIncludeContent,
		arg.TelegramBotToken,
		arg.TelegramChatID,
		arg.AcceptAttachments,
		arg.Captcha,
		arg.NotificationLang,
	)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.AccessKey,
		&i.Active,
		&i.NotifyEmail,
		&i.Recipients,
		&i.EmailIncludeContent,
		&i.StoreSubmissions,
		&i.RetentionDays,
		&i.RedirectUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SlackWebhookUrl,
		&i.TeamsWebhookUrl,
		&i.ChatIncludeContent,
		&i.DiscordWebhookUrl,
		&i.TelegramBotToken,
		&i.TelegramChatID,
		&i.AcceptAttachments,
		&i.Captcha,
		&i.NotificationLang,
	)
	return i, err
}

const deleteForm = `-- name: DeleteForm :exec
DELETE FROM forms WHERE id = $1
`

func (q *Queries) DeleteForm(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteForm, id)
	return err
}

const getFormByAccessKey = `-- name: GetFormByAccessKey :one
SELECT f.id, f.site_id, f.name, f.access_key, f.active, f.notify_email, f.recipients, f.email_include_content, f.store_submissions, f.retention_days, f.redirect_url, f.created_at, f.updated_at, f.slack_webhook_url, f.teams_webhook_url, f.chat_include_content, f.discord_webhook_url, f.telegram_bot_token, f.telegram_chat_id, f.accept_attachments, f.captcha, f.notification_lang, s.name AS site_name, s.domains AS site_domains
FROM forms f
JOIN sites s ON s.id = f.site_id
WHERE f.access_key = $1
`

type GetFormByAccessKeyRow struct {
	ID                  uuid.UUID
	SiteID              uuid.UUID
	Name                string
	AccessKey           string
	Active              bool
	NotifyEmail         bool
	Recipients          []string
	EmailIncludeContent bool
	StoreSubmissions    bool
	RetentionDays       int32
	RedirectUrl         *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	SlackWebhookUrl     *string
	TeamsWebhookUrl     *string
	ChatIncludeContent  bool
	DiscordWebhookUrl   *string
	TelegramBotToken    *string
	TelegramChatID      *string
	AcceptAttachments   bool
	Captcha             bool
	NotificationLang    string
	SiteName            string
	SiteDomains         []string
}

// GetFormByAccessKey sert le point d'entrée public : aucune notion d'utilisateur,
// la clé d'accès désigne le formulaire.
func (q *Queries) GetFormByAccessKey(ctx context.Context, accessKey string) (GetFormByAccessKeyRow, error) {
	row := q.db.QueryRow(ctx, getFormByAccessKey, accessKey)
	var i GetFormByAccessKeyRow
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.AccessKey,
		&i.Active,
		&i.NotifyEmail,
		&i.Recipients,
		&i.EmailIncludeContent,
		&i.StoreSubmissions,
		&i.RetentionDays,
		&i.RedirectUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SlackWebhookUrl,
		&i.TeamsWebhookUrl,
		&i.ChatIncludeContent,
		&i.DiscordWebhookUrl,
		&i.TelegramBotToken,
		&i.TelegramChatID,
		&i.AcceptAttachments,
		&i.Captcha,
		&i.NotificationLang,
		&i.SiteName,
		&i.SiteDomains,
	)
	return i, err
}

const getFormScoped = `-- name: GetFormScoped :one
SELECT f.id, f.site_id, f.name, f.access_key, f.active, f.notify_email, f.recipients, f.email_include_content, f.store_submissions, f.retention_days, f.redirect_url, f.created_at, f.updated_at, f.slack_webhook_url, f.teams_webhook_url, f.chat_include_content, f.discord_webhook_url, f.telegram_bot_token, f.telegram_chat_id, f.accept_attachments, f.captcha, f.notification_lang, s.name AS site_name, s.domains AS site_domains
FROM forms f
JOIN sites s ON s.id = f.site_id
WHERE f.id = $1
  AND ($2::bool OR s.owner_id = $3)
`

type GetFormScopedParams struct {
	ID       uuid.UUID
	IsAdmin  bool
	ViewerID uuid.UUID
}

type GetFormScopedRow struct {
	ID                  uuid.UUID
	SiteID              uuid.UUID
	Name                string
	AccessKey           string
	Active              bool
	NotifyEmail         bool
	Recipients          []string
	EmailIncludeContent bool
	StoreSubmissions    bool
	RetentionDays       int32
	RedirectUrl         *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	SlackWebhookUrl     *string
	TeamsWebhookUrl     *string
	ChatIncludeContent  bool
	DiscordWebhookUrl   *string
	TelegramBotToken    *string
	TelegramChatID      *string
	AcceptAttachments   bool
	Captcha             bool
	NotificationLang    string
	SiteName            string
	SiteDomains         []string
}

// Même règle de cloisonnement que sites.sql : le périmètre du demandeur est
// vérifié dans la requête, via le site propriétaire du formulaire.
func (q *Queries) GetFormScoped(ctx context.Context, arg GetFormScopedParams) (GetFormScopedRow, error) {
	row := q.db.QueryRow(ctx, getFormScoped, arg.ID, arg.IsAdmin, arg.ViewerID)
	var i GetFormScopedRow
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.AccessKey,
		&i.Active,
		&i.NotifyEmail,
		&i.Recipients,
		&i.EmailIncludeContent,
		&i.StoreSubmissions,
		&i.RetentionDays,
		&i.RedirectUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SlackWebhookUrl,
		&i.TeamsWebhookUrl,
		&i.ChatIncludeContent,
		&i.DiscordWebhookUrl,
		&i.TelegramBotToken,
		&i.TelegramChatID,
		&i.AcceptAttachments,
		&i.Captcha,
		&i.NotificationLang,
		&i.SiteName,
		&i.SiteDomains,
	)
	return i, err
}

const listFormsBySite = `-- name: ListFormsBySite :many
SELECT f.id, f.site_id, f.name, f.access_key, f.active, f.notify_email, f.recipients, f.email_include_content, f.store_submissions, f.retention_days, f.redirect_url, f.created_at, f.updated_at, f.slack_webhook_url, f.teams_webhook_url, f.chat_include_content, f.discord_webhook_url, f.telegram_bot_token, f.telegram_chat_id, f.accept_attachments, f.captcha, f.notification_lang,
       (SELECT count(*) FROM submissions sub WHERE sub.form_id = f.id) AS submission_count,
       (SELECT count(*) FROM submissions sub WHERE sub.form_id = f.id AND sub.read_at IS NULL) AS unread_count
FROM forms f
WHERE f.site_id = $1
ORDER BY f.name
`

type ListFormsBySiteRow struct {
	ID                  uuid.UUID
	SiteID              uuid.UUID
	Name                string
	AccessKey           string
	Active              bool
	NotifyEmail         bool
	Recipients          []string
	EmailIncludeContent bool
	StoreSubmissions    bool
	RetentionDays       int32
	RedirectUrl         *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	SlackWebhookUrl     *string
	TeamsWebhookUrl     *string
	ChatIncludeContent  bool
	DiscordWebhookUrl   *string
	TelegramBotToken    *string
	TelegramChatID      *string
	AcceptAttachments   bool
	Captcha             bool
	NotificationLang    string
	SubmissionCount     int64
	UnreadCount         int64
}

func (q *Queries) ListFormsBySite(ctx context.Context, siteID uuid.UUID) ([]ListFormsBySiteRow, error) {
	rows, err := q.db.Query(ctx, listFormsBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFormsBySiteRow
	for rows.Next() {
		var i ListFormsBySiteRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Name,
			&i.AccessKey,
			&i.Active,
			&i.NotifyEmail,
			&i.Recipients,
			&i.EmailIncludeContent,
			&i.StoreSubmissions,
			&i.RetentionDays,
			&i.RedirectUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SlackWebhookUrl,
			&i.TeamsWebhookUrl,
			&i.ChatIncludeContent,
			&i.DiscordWebhookUrl,
			&i.TelegramBotToken,
			&i.TelegramChatID,
			&i.AcceptAttachments,
			&i.Captcha,
			&i.NotificationLang,
			&i.SubmissionCount,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFormsOfSite = `-- name: ListFormsOfSite :many
SELECT id, site_id, name, access_key, active, notify_email, recipients, email_include_content, store_submissions, retention_days, redirect_url, created_at, updated_at, slack_webhook_url, teams_webhook_url, chat_include_content, discord_webhook_url, telegram_bot_token, telegram_chat_id, accept_attachments, captcha, notification_lang FROM forms WHERE site_id = $1 ORDER BY name
`

// ListFormsOfSite et CountFormsBySite servent l'API. Pas de périmètre dans ces
// requêtes : le site vient du jeton, que GetAPITokenByHash a déjà contrôlé.
func (q *Queries) ListFormsOfSite(ctx context.Context, siteID uuid.UUID) ([]Form, error) {
	rows, err := q.db.Query(ctx, listFormsOfSite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Form
	for rows.Next() {
		var i Form
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Name,
			&i.AccessKey,
			&i.Active,
			&i.NotifyEmail,
			&i.Recipients,
			&i.EmailIncludeContent,
			&i.StoreSubmissions,
			&i.RetentionDays,
			&i.RedirectUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SlackWebhookUrl,
			&i.TeamsWebhookUrl,
			&i.ChatIncludeContent,
			&i.DiscordWebhookUrl,
			&i.TelegramBotToken,
			&i.TelegramChatID,
			&i.AcceptAttachments,
			&i.Captcha,
			&i.NotificationLang,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFormAccessKey = `-- name: SetFormAccessKey :exec
UPDATE forms SET access_key = $2, updated_at = now() WHERE id = $1
`

type SetFormAccessKeyParams struct {
	ID        uuid.UUID
	AccessKey string
}

func (q *Queries) SetFormAccessKey(ctx context.Context, arg SetFormAccessKeyParams) error {
	_, err := q.db.Exec(ctx, setFormAccessKey, arg.ID, arg.AccessKey)
	return err
}

const updateForm = `-- name: UpdateForm :exec
UPDATE forms
SET name = $2, active = $3, notify_email = $4, recipients = $5, email_include_content = $6,
    store_submissions = $7, retention_days = $8, redirect_url = $9,
    slack_webhook_url = $10, teams_webhook_url = $11, discord_webhook_url = $12, chat_include_content = $13,
    telegram_bot_token = $14, telegram_chat_id = $15, accept_attachments = $16, captcha = $17,
    notification_lang = $18, updated_at = now()
WHERE id = $1
`

type UpdateFormParams struct {
	ID                  uuid.UUID
	Name                string
	Active              bool
	NotifyEmail         bool
	Recipients          []string
	EmailIncludeContent bool
	StoreSubmissions    bool
	RetentionDays       int32
	RedirectUrl         *string
	SlackWebhookUrl     *string
	TeamsWebhookUrl     *string
	DiscordWebhookUrl   *string
	ChatIncludeContent  bool
	TelegramBotToken    *string
	TelegramChatID      *string
	AcceptAttachments   bool
	Captcha             bool
	NotificationLang    string
}

func (q *Queries) UpdateForm(ctx context.Context, arg UpdateFormParams) error {
	_, err := q.db.Exec(ctx, updateForm,
		arg.ID,
		arg.Name,
		arg.Active,
		arg.NotifyEmail,
		arg.Recipients,
		arg.EmailIncludeContent,
		arg.StoreSubmissions,
		arg.RetentionDays,
		arg.RedirectUrl,
		arg.SlackWebhookUrl,
		arg.TeamsWebhookUrl,
		arg.DiscordWebhookUrl,
		arg.ChatIncludeContent,
		arg.TelegramBotToken,
		arg.TelegramChatID,
		arg.AcceptAttachments,
		arg.Captcha,
		arg.NotificationLang,
	)
	return err
}
