// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID         uuid.UUID
	SiteID     uuid.UUID
	UserID     uuid.UUID
	Name       string
	TokenHash  string
	ExpiresAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	CreatedAt  time.Time
}

type Attachment struct {
	ID           uuid.UUID
	SubmissionID uuid.UUID
	Position     int16
	Filename     string
	Size         int64
	Content      []byte
}

type AuditLog struct {
	ID        uuid.UUID
	ActorID   pgtype.UUID
	Action    string
	Entity    string
	EntityID  pgtype.UUID
	Detail    *string
	CreatedAt time.Time
}

type Form struct {
	ID                  uuid.UUID
	SiteID              uuid.UUID
	Name                string
	AccessKey           string
	Active              bool
	NotifyEmail         bool
	Recipients          []string
	EmailIncludeContent bool
	StoreSubmissions    bool
	RetentionDays       int32
	RedirectUrl         *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	SlackWebhookUrl     *string
	TeamsWebhookUrl     *string
	ChatIncludeContent  bool
	DiscordWebhookUrl   *string
	TelegramBotToken    *string
	TelegramChatID      *string
	AcceptAttachments   bool
	Captcha             bool
	NotificationLang    string
}

type Organisation struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

type PasswordResetToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	UsedAt    pgtype.Timestamptz
	CreatedAt time.Time
}

type Session struct {
	Token  string
	Data   []byte
	Expiry time.Time
}

type Site struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Name      string
	Domains   []string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SiteReadGrant struct {
	SiteID    uuid.UUID
	UserID    uuid.UUID
	GrantedBy pgtype.UUID
	CreatedAt time.Time
}

type Submission struct {
	ID        uuid.UUID
	FormID    uuid.UUID
	Payload   string
	ReadAt    pgtype.Timestamptz
	CreatedAt time.Time
}

type TotpBackupCode struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CodeHash  string
	UsedAt    pgtype.Timestamptz
	CreatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	Name         string
	Role         string
	PasswordHash string
	Active       bool
	TotpSecret   *string
	TotpEnabled  bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	OrgID        pgtype.UUID
}
