// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organisations.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOrganisation = `-- name: CreateOrganisation :one
INSERT INTO organisations (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreateOrganisation(ctx context.Context, name string) (Organisation, error) {
	row := q.db.QueryRow(ctx, createOrganisation, name)
	var i Organisation
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listOrganisations = `-- name: ListOrganisations :many
SELECT o.id, o.name, o.created_at, a.email AS admin_email
FROM organisations o
LEFT JOIN users a ON a.org_id = o.id AND a.role = 'admin_orga'
ORDER BY o.name, o.id
`

type ListOrganisationsRow struct {
	ID         uuid.UUID
	Name       string
	CreatedAt  time.Time
	AdminEmail *string
}

// L'administrateur de plateforme voit les organisations et l'adresse de leur
// administrateur, et rien de leurs comptes ni de leurs sites.
func (q *Queries) ListOrganisations(ctx context.Context) ([]ListOrganisationsRow, error) {
	rows, err := q.db.Query(ctx, listOrganisations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganisationsRow
	for rows.Next() {
		var i ListOrganisationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.AdminEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
