// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_resets.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumePasswordResets = `-- name: ConsumePasswordResets :exec
UPDATE password_reset_tokens SET used_at = now() WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) ConsumePasswordResets(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumePasswordResets, userID)
	return err
}

const countRecentPasswordResets = `-- name: CountRecentPasswordResets :one
SELECT count(*) FROM password_reset_tokens
WHERE user_id = $1 AND created_at > now() - interval '15 minutes'
`

func (q *Queries) CountRecentPasswordResets(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentPasswordResets, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPasswordReset = `-- name: CreatePasswordReset :exec
INSERT INTO password_reset_tokens (user_id, token_hash, expires_at) VALUES ($1, $2, $3)
`

type CreatePasswordResetParams struct {
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) error {
	_, err := q.db.Exec(ctx, createPasswordReset, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const deleteExpiredPasswordResets = `-- name: DeleteExpiredPasswordResets :exec
DELETE FROM password_reset_tokens WHERE expires_at < now() - interval '1 day'
`

func (q *Queries) DeleteExpiredPasswordResets(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredPasswordResets)
	return err
}

const getPasswordResetByHash = `-- name: GetPasswordResetByHash :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at
FROM password_reset_tokens
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > now()
`

func (q *Queries) GetPasswordResetByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetByHash, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}
