// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sites.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countSitesScoped = `-- name: CountSitesScoped :one
SELECT count(*) FROM sites s
WHERE ($1::bool OR s.owner_id = $2)
  AND ($3::text IS NULL
       OR s.name ILIKE '%' || $3 || '%'
       OR array_to_string(s.domains, ' ') ILIKE '%' || $3 || '%')
`

type CountSitesScopedParams struct {
	IsAdmin  bool
	ViewerID uuid.UUID
	Search   *string
}

func (q *Queries) CountSitesScoped(ctx context.Context, arg CountSitesScopedParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSitesScoped, arg.IsAdmin, arg.ViewerID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSite = `-- name: CreateSite :one
INSERT INTO sites (owner_id, name, domains)
VALUES ($1, $2, $3)
RETURNING id, owner_id, name, domains, created_at, updated_at
`

type CreateSiteParams struct {
	OwnerID uuid.UUID
	Name    string
	Domains []string
}

func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, createSite, arg.OwnerID, arg.Name, arg.Domains)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Domains,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSiteScoped = `-- name: DeleteSiteScoped :execrows
DELETE FROM sites
WHERE id = $1
  AND ($2::bool OR owner_id = $3)
`

type DeleteSiteScopedParams struct {
	ID       uuid.UUID
	IsAdmin  bool
	ViewerID uuid.UUID
}

func (q *Queries) DeleteSiteScoped(ctx context.Context, arg DeleteSiteScopedParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSiteScoped, arg.ID, arg.IsAdmin, arg.ViewerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSiteOwnerEmail = `-- name: GetSiteOwnerEmail :one
SELECT u.email FROM sites s JOIN users u ON u.id = s.owner_id WHERE s.id = $1
`

func (q *Queries) GetSiteOwnerEmail(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getSiteOwnerEmail, id)
	var email string
	err := row.Scan(&email)
	return email, err
}

const getSiteScoped = `-- name: GetSiteScoped :one
SELECT s.id, s.owner_id, s.name, s.domains, s.created_at, s.updated_at, u.name AS owner_name
FROM sites s
JOIN users u ON u.id = s.owner_id
WHERE s.id = $1
  AND ($2::bool OR s.owner_id = $3)
`

type GetSiteScopedParams struct {
	ID       uuid.UUID
	IsAdmin  bool
	ViewerID uuid.UUID
}

type GetSiteScopedRow struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Name      string
	Domains   []string
	CreatedAt time.Time
	UpdatedAt time.Time
	OwnerName string
}

// Cloisonnement : toute lecture ou écriture d'un site porte le périmètre du
// demandeur (viewer_id / is_admin) dans la requête. Un membre ne voit que les
// sites dont il est propriétaire ; un administrateur les voit tous.
func (q *Queries) GetSiteScoped(ctx context.Context, arg GetSiteScopedParams) (GetSiteScopedRow, error) {
	row := q.db.QueryRow(ctx, getSiteScoped, arg.ID, arg.IsAdmin, arg.ViewerID)
	var i GetSiteScopedRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Domains,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerName,
	)
	return i, err
}

const listSitesScoped = `-- name: ListSitesScoped :many
SELECT s.id, s.owner_id, s.name, s.domains, s.created_at, s.updated_at, u.name AS owner_name,
       (SELECT count(*) FROM forms f WHERE f.site_id = s.id) AS form_count,
       (SELECT count(*) FROM submissions sub JOIN forms f ON f.id = sub.form_id
         WHERE f.site_id = s.id AND sub.read_at IS NULL) AS unread_count
FROM sites s
JOIN users u ON u.id = s.owner_id
WHERE ($1::bool OR s.owner_id = $2)
  AND ($3::text IS NULL
       OR s.name ILIKE '%' || $3 || '%'
       OR array_to_string(s.domains, ' ') ILIKE '%' || $3 || '%')
ORDER BY s.name
LIMIT $5 OFFSET $4
`

type ListSitesScopedParams struct {
	IsAdmin    bool
	ViewerID   uuid.UUID
	Search     *string
	PageOffset int32
	PageLimit  int32
}

type ListSitesScopedRow struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	Name        string
	Domains     []string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	OwnerName   string
	FormCount   int64
	UnreadCount int64
}

func (q *Queries) ListSitesScoped(ctx context.Context, arg ListSitesScopedParams) ([]ListSitesScopedRow, error) {
	rows, err := q.db.Query(ctx, listSitesScoped,
		arg.IsAdmin,
		arg.ViewerID,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSitesScopedRow
	for rows.Next() {
		var i ListSitesScopedRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Domains,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
			&i.FormCount,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSiteOwner = `-- name: SetSiteOwner :exec
UPDATE sites SET owner_id = $2, updated_at = now() WHERE id = $1
`

type SetSiteOwnerParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) SetSiteOwner(ctx context.Context, arg SetSiteOwnerParams) error {
	_, err := q.db.Exec(ctx, setSiteOwner, arg.ID, arg.OwnerID)
	return err
}

const updateSiteScoped = `-- name: UpdateSiteScoped :execrows
UPDATE sites SET name = $1, domains = $2, updated_at = now()
WHERE id = $3
  AND ($4::bool OR owner_id = $5)
`

type UpdateSiteScopedParams struct {
	Name     string
	Domains  []string
	ID       uuid.UUID
	IsAdmin  bool
	ViewerID uuid.UUID
}

func (q *Queries) UpdateSiteScoped(ctx context.Context, arg UpdateSiteScopedParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSiteScoped,
		arg.Name,
		arg.Domains,
		arg.ID,
		arg.IsAdmin,
		arg.ViewerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
