// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: submissions.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSubmissionsByForm = `-- name: CountSubmissionsByForm :one
SELECT count(*) FROM submissions WHERE form_id = $1
`

func (q *Queries) CountSubmissionsByForm(ctx context.Context, formID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSubmissionsByForm, formID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (id, form_id, payload)
VALUES ($1, $2, $3)
RETURNING id, form_id, payload, read_at, created_at
`

type CreateSubmissionParams struct {
	ID      uuid.UUID
	FormID  uuid.UUID
	Payload string
}

// L'identifiant vient de l'application : elle doit le connaître avant
// l'insertion, pour écarter de FormStorageBytes une soumission qu'elle est en
// train de conserver.
func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, createSubmission, arg.ID, arg.FormID, arg.Payload)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Payload,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSubmission = `-- name: DeleteSubmission :exec
DELETE FROM submissions WHERE id = $1
`

func (q *Queries) DeleteSubmission(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubmission, id)
	return err
}

const deleteSubmissionsByForm = `-- name: DeleteSubmissionsByForm :execrows
DELETE FROM submissions WHERE form_id = $1
`

func (q *Queries) DeleteSubmissionsByForm(ctx context.Context, formID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSubmissionsByForm, formID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const formStorageBytes = `-- name: FormStorageBytes :one
SELECT ((SELECT coalesce(sum(octet_length(sub.payload)), 0) FROM submissions sub
         WHERE sub.form_id = $1 AND sub.id <> ALL(coalesce($2::uuid[], '{}')))
      + (SELECT coalesce(sum(a.size), 0) FROM attachments a
         JOIN submissions sub ON sub.id = a.submission_id
         WHERE sub.form_id = $1 AND sub.id <> ALL(coalesce($2::uuid[], '{}'))))::bigint
`

type FormStorageBytesParams struct {
	FormID  uuid.UUID
	Pending []uuid.UUID
}

// FormStorageBytes mesure le poids des soumissions conservées d'un formulaire :
// leur contenu chiffré tel que stocké, et la taille en clair de leurs pièces
// jointes. Deux sommes séparées : une sous-requête par soumission coûterait un
// sondage d'index pour chacune. L'application ne l'appelle pas à chaque envoi,
// elle en garde le résultat (voir formUsage). pending désigne les soumissions
// qu'elle est en train de conserver : elle les compte à part, et les retrouver
// ici, validées entre-temps, les compterait deux fois. Le coalesce couvre une
// liste absente : comparé à NULL, aucun identifiant ne serait retenu, et la
// mesure vaudrait zéro.
func (q *Queries) FormStorageBytes(ctx context.Context, arg FormStorageBytesParams) (int64, error) {
	row := q.db.QueryRow(ctx, formStorageBytes, arg.FormID, arg.Pending)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getSubmissionScoped = `-- name: GetSubmissionScoped :one
SELECT sub.id, sub.form_id, sub.payload, sub.read_at, sub.created_at, f.name AS form_name, f.site_id, s.name AS site_name
FROM submissions sub
JOIN forms f ON f.id = sub.form_id
JOIN sites s ON s.id = f.site_id
WHERE sub.id = $1
  AND ($2::bool OR s.owner_id = $3)
`

type GetSubmissionScopedParams struct {
	ID       uuid.UUID
	IsAdmin  bool
	ViewerID uuid.UUID
}

type GetSubmissionScopedRow struct {
	ID        uuid.UUID
	FormID    uuid.UUID
	Payload   string
	ReadAt    pgtype.Timestamptz
	CreatedAt time.Time
	FormName  string
	SiteID    uuid.UUID
	SiteName  string
}

func (q *Queries) GetSubmissionScoped(ctx context.Context, arg GetSubmissionScopedParams) (GetSubmissionScopedRow, error) {
	row := q.db.QueryRow(ctx, getSubmissionScoped, arg.ID, arg.IsAdmin, arg.ViewerID)
	var i GetSubmissionScopedRow
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Payload,
		&i.ReadAt,
		&i.CreatedAt,
		&i.FormName,
		&i.SiteID,
		&i.SiteName,
	)
	return i, err
}

const listAllSubmissionsByForm = `-- name: ListAllSubmissionsByForm :many
SELECT id, form_id, payload, read_at, created_at FROM submissions WHERE form_id = $1 ORDER BY created_at, id
`

// ListAllSubmissionsByForm alimente les exports (ordre chronologique).
// L'identifiant départage deux soumissions reçues au même instant : l'ordre
// des lignes ne varie pas d'un export à l'autre.
func (q *Queries) ListAllSubmissionsByForm(ctx context.Context, formID uuid.UUID) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listAllSubmissionsByForm, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.Payload,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionsByForm = `-- name: ListSubmissionsByForm :many
SELECT id, form_id, payload, read_at, created_at FROM submissions
WHERE form_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListSubmissionsByFormParams struct {
	FormID     uuid.UUID
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListSubmissionsByForm(ctx context.Context, arg ListSubmissionsByFormParams) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listSubmissionsByForm, arg.FormID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.Payload,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFormSubmissionsRead = `-- name: MarkFormSubmissionsRead :exec
UPDATE submissions SET read_at = now() WHERE form_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkFormSubmissionsRead(ctx context.Context, formID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markFormSubmissionsRead, formID)
	return err
}

const markSubmissionRead = `-- name: MarkSubmissionRead :exec
UPDATE submissions SET read_at = now() WHERE id = $1 AND read_at IS NULL
`

func (q *Queries) MarkSubmissionRead(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markSubmissionRead, id)
	return err
}

const purgeExpiredSubmissions = `-- name: PurgeExpiredSubmissions :execrows
DELETE FROM submissions sub
USING forms f
WHERE f.id = sub.form_id
  AND f.retention_days > 0
  AND sub.created_at < now() - make_interval(days => f.retention_days)
`

// PurgeExpiredSubmissions applique la durée de conservation de chaque formulaire
// (retention_days = 0 : conservation sans limite).
func (q *Queries) PurgeExpiredSubmissions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeExpiredSubmissions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
