// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT count(*) FROM users WHERE role = 'admin' AND active = TRUE
`

func (q *Queries) CountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersMatching = `-- name: CountUsersMatching :one
SELECT count(*) FROM users u
WHERE ($1::text IS NULL OR u.name ILIKE '%' || $1 || '%' OR u.email ILIKE '%' || $1 || '%')
`

func (q *Queries) CountUsersMatching(ctx context.Context, search *string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersMatching, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, role, password_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, email, name, role, password_hash, active, totp_secret, totp_enabled, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	Name         string
	Role         string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.Role,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.Active,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const disableUserTOTP = `-- name: DisableUserTOTP :exec
UPDATE users SET totp_secret = NULL, totp_enabled = FALSE, updated_at = now() WHERE id = $1
`

func (q *Queries) DisableUserTOTP(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, disableUserTOTP, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, role, password_hash, active, totp_secret, totp_enabled, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.Active,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, role, password_hash, active, totp_secret, totp_enabled, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.Active,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveUsers = `-- name: ListActiveUsers :many
SELECT id, email, name, role, password_hash, active, totp_secret, totp_enabled, created_at, updated_at FROM users WHERE active = TRUE ORDER BY name
`

func (q *Queries) ListActiveUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listActiveUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.PasswordHash,
			&i.Active,
			&i.TotpSecret,
			&i.TotpEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT u.id, u.email, u.name, u.role, u.password_hash, u.active, u.totp_secret, u.totp_enabled, u.created_at, u.updated_at, (SELECT count(*) FROM sites s WHERE s.owner_id = u.id) AS site_count
FROM users u
WHERE ($1::text IS NULL OR u.name ILIKE '%' || $1 || '%' OR u.email ILIKE '%' || $1 || '%')
ORDER BY u.name
LIMIT $3 OFFSET $2
`

type ListUsersParams struct {
	Search     *string
	PageOffset int32
	PageLimit  int32
}

type ListUsersRow struct {
	ID           uuid.UUID
	Email        string
	Name         string
	Role         string
	PasswordHash string
	Active       bool
	TotpSecret   *string
	TotpEnabled  bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	SiteCount    int64
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Search, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.PasswordHash,
			&i.Active,
			&i.TotpSecret,
			&i.TotpEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SiteCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserActive = `-- name: SetUserActive :exec
UPDATE users SET active = $2, updated_at = now() WHERE id = $1
`

type SetUserActiveParams struct {
	ID     uuid.UUID
	Active bool
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) error {
	_, err := q.db.Exec(ctx, setUserActive, arg.ID, arg.Active)
	return err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = now() WHERE id = $1
`

type SetUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const setUserRole = `-- name: SetUserRole :exec
UPDATE users SET role = $2, updated_at = now() WHERE id = $1
`

type SetUserRoleParams struct {
	ID   uuid.UUID
	Role string
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) error {
	_, err := q.db.Exec(ctx, setUserRole, arg.ID, arg.Role)
	return err
}

const setUserTOTP = `-- name: SetUserTOTP :exec
UPDATE users SET totp_secret = $2, totp_enabled = TRUE, updated_at = now() WHERE id = $1
`

type SetUserTOTPParams struct {
	ID         uuid.UUID
	TotpSecret *string
}

func (q *Queries) SetUserTOTP(ctx context.Context, arg SetUserTOTPParams) error {
	_, err := q.db.Exec(ctx, setUserTOTP, arg.ID, arg.TotpSecret)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE users SET email = $2, updated_at = now() WHERE id = $1
`

type UpdateUserEmailParams struct {
	ID    uuid.UUID
	Email string
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.Exec(ctx, updateUserEmail, arg.ID, arg.Email)
	return err
}

const updateUserName = `-- name: UpdateUserName :exec
UPDATE users SET name = $2, updated_at = now() WHERE id = $1
`

type UpdateUserNameParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error {
	_, err := q.db.Exec(ctx, updateUserName, arg.ID, arg.Name)
	return err
}
