// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOrgUsersMatching = `-- name: CountOrgUsersMatching :one
SELECT count(*) FROM users u
WHERE u.org_id = $1
  AND ($2::text IS NULL OR u.name ILIKE '%' || $2 || '%' OR u.email ILIKE '%' || $2 || '%')
`

type CountOrgUsersMatchingParams struct {
	OrgID  pgtype.UUID
	Search *string
}

func (q *Queries) CountOrgUsersMatching(ctx context.Context, arg CountOrgUsersMatchingParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrgUsersMatching, arg.OrgID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, role, password_hash, org_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, name, role, password_hash, active, totp_secret, totp_enabled, created_at, updated_at, org_id
`

type CreateUserParams struct {
	Email        string
	Name         string
	Role         string
	PasswordHash string
	OrgID        pgtype.UUID
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.Role,
		arg.PasswordHash,
		arg.OrgID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.Active,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
	)
	return i, err
}

const deleteUserScoped = `-- name: DeleteUserScoped :execrows
DELETE FROM users WHERE id = $1 AND org_id = $2 AND role = 'user'
`

type DeleteUserScopedParams struct {
	ID         uuid.UUID
	AdminOrgID pgtype.UUID
}

func (q *Queries) DeleteUserScoped(ctx context.Context, arg DeleteUserScopedParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserScoped, arg.ID, arg.AdminOrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const demoteOrgAdmin = `-- name: DemoteOrgAdmin :exec
UPDATE users SET role = 'user', updated_at = now() WHERE org_id = $1 AND role = 'admin_orga'
`

// Remplacement de l'administrateur d'une organisation : l'ancien redevient user.
func (q *Queries) DemoteOrgAdmin(ctx context.Context, orgID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, demoteOrgAdmin, orgID)
	return err
}

const disableUserTOTP = `-- name: DisableUserTOTP :exec
UPDATE users SET totp_secret = NULL, totp_enabled = FALSE, updated_at = now() WHERE id = $1
`

func (q *Queries) DisableUserTOTP(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, disableUserTOTP, id)
	return err
}

const disableUserTOTPScoped = `-- name: DisableUserTOTPScoped :execrows
UPDATE users SET totp_secret = NULL, totp_enabled = FALSE, updated_at = now()
WHERE id = $1 AND org_id = $2 AND role = 'user'
`

type DisableUserTOTPScopedParams struct {
	ID         uuid.UUID
	AdminOrgID pgtype.UUID
}

func (q *Queries) DisableUserTOTPScoped(ctx context.Context, arg DisableUserTOTPScopedParams) (int64, error) {
	result, err := q.db.Exec(ctx, disableUserTOTPScoped, arg.ID, arg.AdminOrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOrgUser = `-- name: GetOrgUser :one
SELECT id, email, name, role, password_hash, active, totp_secret, totp_enabled, created_at, updated_at, org_id FROM users WHERE id = $1 AND org_id = $2 AND role = 'user'
`

type GetOrgUserParams struct {
	ID    uuid.UUID
	OrgID pgtype.UUID
}

// Le compte désigné dans un écran d'administration de l'organisation : un compte
// user de cette organisation, sinon rien (404).
func (q *Queries) GetOrgUser(ctx context.Context, arg GetOrgUserParams) (User, error) {
	row := q.db.QueryRow(ctx, getOrgUser, arg.ID, arg.OrgID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.Active,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, role, password_hash, active, totp_secret, totp_enabled, created_at, updated_at, org_id FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.Active,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, role, password_hash, active, totp_secret, totp_enabled, created_at, updated_at, org_id FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.Active,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
	)
	return i, err
}

const listActiveOrgUsers = `-- name: ListActiveOrgUsers :many
SELECT id, email, name, role, password_hash, active, totp_secret, totp_enabled, created_at, updated_at, org_id FROM users WHERE org_id = $1 AND active = TRUE ORDER BY name
`

func (q *Queries) ListActiveOrgUsers(ctx context.Context, orgID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listActiveOrgUsers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.PasswordHash,
			&i.Active,
			&i.TotpSecret,
			&i.TotpEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgUsers = `-- name: ListOrgUsers :many
SELECT u.id, u.email, u.name, u.role, u.password_hash, u.active, u.totp_secret, u.totp_enabled, u.created_at, u.updated_at, u.org_id, (SELECT count(*) FROM sites s WHERE s.owner_id = u.id) AS site_count
FROM users u
WHERE u.org_id = $1
  AND ($2::text IS NULL OR u.name ILIKE '%' || $2 || '%' OR u.email ILIKE '%' || $2 || '%')
ORDER BY u.name
LIMIT $4 OFFSET $3
`

type ListOrgUsersParams struct {
	OrgID      pgtype.UUID
	Search     *string
	PageOffset int32
	PageLimit  int32
}

type ListOrgUsersRow struct {
	ID           uuid.UUID
	Email        string
	Name         string
	Role         string
	PasswordHash string
	Active       bool
	TotpSecret   *string
	TotpEnabled  bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	OrgID        pgtype.UUID
	SiteCount    int64
}

// Les comptes d'une organisation, pour son administrateur. Le périmètre est
// l'organisation de l'administrateur, passée par l'application.
func (q *Queries) ListOrgUsers(ctx context.Context, arg ListOrgUsersParams) ([]ListOrgUsersRow, error) {
	rows, err := q.db.Query(ctx, listOrgUsers,
		arg.OrgID,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgUsersRow
	for rows.Next() {
		var i ListOrgUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.PasswordHash,
			&i.Active,
			&i.TotpSecret,
			&i.TotpEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrgID,
			&i.SiteCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserActiveScoped = `-- name: SetUserActiveScoped :execrows
UPDATE users SET active = $1, updated_at = now()
WHERE id = $2 AND org_id = $3 AND role = 'user'
`

type SetUserActiveScopedParams struct {
	Active     bool
	ID         uuid.UUID
	AdminOrgID pgtype.UUID
}

// Les écritures sur un compte ne visent que les comptes user de l'organisation de
// l'administrateur (sqlc.arg('admin_org_id')). Un compte hors périmètre n'est pas
// modifié, et le nombre de lignes le dit à l'application.
func (q *Queries) SetUserActiveScoped(ctx context.Context, arg SetUserActiveScopedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserActiveScoped, arg.Active, arg.ID, arg.AdminOrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = now() WHERE id = $1
`

type SetUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const setUserPasswordScoped = `-- name: SetUserPasswordScoped :execrows
UPDATE users SET password_hash = $1, updated_at = now()
WHERE id = $2 AND org_id = $3 AND role = 'user'
`

type SetUserPasswordScopedParams struct {
	PasswordHash string
	ID           uuid.UUID
	AdminOrgID   pgtype.UUID
}

func (q *Queries) SetUserPasswordScoped(ctx context.Context, arg SetUserPasswordScopedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserPasswordScoped, arg.PasswordHash, arg.ID, arg.AdminOrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUserTOTP = `-- name: SetUserTOTP :exec
UPDATE users SET totp_secret = $2, totp_enabled = TRUE, updated_at = now() WHERE id = $1
`

type SetUserTOTPParams struct {
	ID         uuid.UUID
	TotpSecret *string
}

func (q *Queries) SetUserTOTP(ctx context.Context, arg SetUserTOTPParams) error {
	_, err := q.db.Exec(ctx, setUserTOTP, arg.ID, arg.TotpSecret)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE users SET email = $2, updated_at = now() WHERE id = $1
`

type UpdateUserEmailParams struct {
	ID    uuid.UUID
	Email string
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.Exec(ctx, updateUserEmail, arg.ID, arg.Email)
	return err
}

const updateUserName = `-- name: UpdateUserName :exec
UPDATE users SET name = $2, updated_at = now() WHERE id = $1
`

type UpdateUserNameParams struct {
	ID   uuid.UUID
	Name string
}

// Opérations sur son propre compte, depuis /account ou la réinitialisation.
func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error {
	_, err := q.db.Exec(ctx, updateUserName, arg.ID, arg.Name)
	return err
}

const updateUserNameScoped = `-- name: UpdateUserNameScoped :execrows
UPDATE users SET name = $1, updated_at = now()
WHERE id = $2 AND org_id = $3 AND role = 'user'
`

type UpdateUserNameScopedParams struct {
	Name       string
	ID         uuid.UUID
	AdminOrgID pgtype.UUID
}

func (q *Queries) UpdateUserNameScoped(ctx context.Context, arg UpdateUserNameScopedParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserNameScoped, arg.Name, arg.ID, arg.AdminOrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
